# Generated by Django 4.2.11 on 2026-03-24 19:25

from django.db import migrations, models
import django.db.models.deletion
import mcp.Processor.models
import mcp.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0001_initial'),
        ('Resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=512)),
                ('target', models.CharField(max_length=50)),
                ('value_map', mcp.fields.MapField(blank=True, default=mcp.fields.defaultdict, editable=True)),
                ('built_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ran_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reported_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('released_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('manual', models.BooleanField()),
                ('user', models.CharField(max_length=150)),
                ('package_file_map', mcp.fields.MapField(blank=True, default=mcp.fields.defaultdict, editable=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('build', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='Project.build')),
                ('commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.commit')),
                ('network_list', models.ManyToManyField(to='Resource.network')),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='Project.project')),
            ],
            options={
                'permissions': (('can_build', 'Can queue builds'), ('can_ran', 'Can Flag a Build Resource as ran'), ('can_ack', 'Can Acknoledge a failed Build Resource')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_map', mcp.fields.MapField(blank=True, default=mcp.fields.defaultdict, editable=True)),
                ('tag', models.CharField(max_length=10)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Project.commit')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=512)),
                ('target', models.CharField(max_length=50)),
                ('priority', models.IntegerField(default=50)),
                ('manual', models.BooleanField()),
                ('user', models.CharField(max_length=150)),
                ('resource_status_map', mcp.fields.MapField(blank=True, default=mcp.fields.defaultdict, editable=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('build', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Project.build')),
                ('commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.commit')),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Processor.promotion')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PromotionBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.build')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Processor.promotion')),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('promotion', 'build')},
            },
        ),
        migrations.AddField(
            model_name='promotion',
            name='status',
            field=models.ManyToManyField(through='Processor.PromotionBuild', to='Project.build'),
        ),
        migrations.CreateModel(
            name='BuildJobResourceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blueprint', models.CharField(max_length=40)),
                ('_config_values', mcp.fields.MapField(blank=True, default=mcp.fields.defaultdict, editable=True)),
                ('auto_run', models.BooleanField(default=False)),
                ('auto_provision', models.BooleanField(default=True)),
                ('cookie', models.CharField(default=mcp.Processor.models.getCookie, max_length=36)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('new', 'new'), ('allocated', 'allocated'), ('building', 'building'), ('built', 'built'), ('ran', 'ran'), ('releasing', 'releasing'), ('released', 'released')], default='new', max_length=9)),
                ('message', models.CharField(blank=True, default='', max_length=200)),
                ('success', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('buildjob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Processor.buildjob')),
                ('resource_instance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Resource.resourceinstance')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='buildjob',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Processor.promotion'),
        ),
        migrations.AddField(
            model_name='buildjob',
            name='resources',
            field=models.ManyToManyField(through='Processor.BuildJobResourceInstance', to='Resource.resourceinstance'),
        ),
    ]
