#!/usr/bin/env python3
import os

os.environ.setdefault( 'DJANGO_SETTINGS_MODULE', 'mcp.settings' )

import django
django.setup()

import sys
import argparse
import cinp
from datetime import datetime, timezone
from prettytable import PrettyTable

from mcp.Project.models import Project, Build, BuildResource
from mcp.Resource.models import Site, Network, DynamicResource, DynamicResourceSite
from mcp.lib.t3kton import getContractor

parser = argparse.ArgumentParser( description='resource manager - add/remove sites, networks, resources' )
task = parser.add_mutually_exclusive_group( required=True )

task.add_argument( '--site-list', help='List the Curent Sites', action='store_true' )
task.add_argument( '--site-add', help='Add a Site, name is required, should be the site name on Contractor', action='store_true' )
task.add_argument( '--site-remove', help='Remove a Site, this should be the site name in MCP', metavar='SITE NAME' )

task.add_argument( '--network-list', help='List the Curent Networks in specified Site', action='store_true' )
task.add_argument( '--network-add', help='Add a Network, site, network, and addresss-block are required', action='store_true' )
task.add_argument( '--network-remove', help='Remove a Network, this should be the network name in MCP', metavar='NETWORK NAME' )

task.add_argument( '--dynamic-resource-list', help='List the Curent Dynamic Resources', action='store_true' )
task.add_argument( '--dynamic-resource-add', help='Add a Dynamic Resources, name and description are required', action='store_true' )
task.add_argument( '--dynamic-resource-remove', help='Remove a Dynamic Resource, this should be the resource name in MCP', metavar='RESOURCE NAME' )

task.add_argument( '--dynamic-resource-attach', help='Attach Site/Complex to a Dynamic Resource, name, site and complex are required', action='store_true'  )
task.add_argument( '--dynamic-resource-detach', help='Detach Site/Complex from a Dynamic Resource, name and site are required', action='store_true'  )

task.add_argument( '--dynamic-resource-build-ahead', help='Set the number of resources to build ahead, name, blueprint, and build-ahead-count, set count to 0 to remove', action='store_true'  )

# this one is a hack and is temporary until the dynamic/bluprint/stuff mess is figured out
task.add_argument( '--update-builtin', help='Add the blueprint to the Builtin project', metavar='BLUEPRINT NAME' )

# arguments for various tasks
parser.add_argument( '--name', help='Name of resource' )
parser.add_argument( '--description', help='Description of resource' )
parser.add_argument( '--site', help='Site for required operations', metavar='SITE NAME' )
parser.add_argument( '--network', help='Network Contractor id for required operations', metavar='NETWORK ID' )
parser.add_argument( '--address-block', help='Address Block Contractor id for required operations', metavar='ADDRESSBLOCK ID' )
parser.add_argument( '--monolithic', help='Flag the Network as Monolithic', action='store_true' )
parser.add_argument( '--complex', help='Complex Contractor id for required operations', metavar='COMPLEX ID' )
parser.add_argument( '--blueprint', help='Blueprint of dynamic resource entries to pre-build' )
parser.add_argument( '--build-ahead-count', help='Number of dynamic resource entries to pre-build', type=int, default=0 )

parser.add_argument( '--json', help='Output lists as JSON instead of a table', action='store_true' )


args = parser.parse_args()

site = None
if args.site:
  try:
    site = Site.objects.get( name=args.site )
  except Site.DoesNotExist:
    print( 'Site "{0}" not found in MCP'.format( args.site ) )
    sys.exit( 1 )

# list operations
if args.site_list or args.network_list or args.dynamic_resource_list:
  table = PrettyTable()
  if args.site_list:
    table.field_names = [ 'Name' ]
    for site in Site.objects.all().order_by( 'pk' ):
      table.add_row( [ site.name ] )

  if args.network_list:
    if site is None:
        print( 'Site Required' )
        sys.exit( 1 )

    table.field_names = [ 'Name', 'Size', 'Monolithic', 'Contractor Address Block Id', 'Contractor Network Id', 'In Use' ]
    for network in Network.objects.filter( site=site ):
      table.add_row( [ network.name, network.size, network.monolithic, network.contractor_addressblock_id, network.contractor_network_id, network.buildjob_set.count() != 0 ] )

  if args.dynamic_resource_list:
    table.field_names = [ 'Name', 'Description', 'BluePrint/Build Ahead Count', 'Site/Complex Map' ]
    for resource in DynamicResource.objects.all():
      site_complex_list = [ '{0}:{1}'.format( i.site.name, i.complex_id ) for i in resource.dynamicresourcesite_set.all() ]
      build_ahead_list = [ '{0}:{1}'.format( k, v ) for k, v in resource.build_ahead_count_map.items() ]
      table.add_row( [ resource.name, resource.description, ' '.join( build_ahead_list ), ' '.join( site_complex_list ) ] )

  table.sortby = 'Name'

  if args.json:
    print( table.get_json_string() )
  else:
    print( table )

    sys.exit( 0 )

contractor = getContractor()

# site operations
if args.site_add:
  if not args.name:
    print( 'Name Required' )
    sys.exit( 1 )

  try:
    Site.objects.get( name=args.name )
    print( 'Site with Name "{0}" Already Exists'.format( args.name ) )
    sys.exit( 1 )

  except Site.DoesNotExist:
    pass

  try:
    contractor_site = contractor.getSite( args.name )
  except cinp.client.NotFound:
    print( 'Site "{0}" not found on Contractor'.format( args.name ) )
    sys.exit( 1 )

  site = Site()
  site.name = args.name
  site.full_clean()
  site.save()

  print( 'Site "{0}" Created.'.format( site.name ) )
  sys.exit( 0 )

if args.site_remove:
  try:
    site = Site.objects.get( name=args.site_remove )
  except Site.DoesNotExist:
    print( 'Site "{0}" not found in MCP'.format( args.site_remove ) )
    sys.exit( 1 )

  site.delete()
  print( 'Site "{0}" deleted.'.format( args.site_remove ) )
  sys.exit( 0 )

# network operations
if args.network_add:
  if not site or not args.network or not args.address_block:
    print( 'Site, Network, and Address Block Required' )
    sys.exit( 1 )

  try:
    contractor_network = contractor.getNetwork( args.network )
  except cinp.client.NotFound:
    print( 'Network "{0}" not found on Contractor'.format( args.network ) )
    sys.exit( 1 )

  if contractor_network[ 'site' ].split( ':' )[1] != site.name:
    print( 'Network "{0}" does not belong to site "{1}"'.format( args.network, args.site ) )
    sys.exit( 1 )

  try:
    contractor_addressblock = contractor.getAddressBlock( args.address_block )
  except cinp.client.NotFound:
    print( 'AddressBlock "{0}" not found on Contractor'.format( args.address_block ) )
    sys.exit( 1 )

  if '/api/v1/Utilities/AddressBlock:{0}:'.format( args.address_block ) not in contractor_network[ 'address_block_list' ]:
    print( 'No Linkage between AddressBlock "{0}" and Network "{1}"'.format( args.address_block, args.network ) )
    sys.exit( 1 )

  name = '{0}-{1}'.format( contractor_network[ 'name' ], contractor_addressblock[ 'name' ] )

  try:
    Network.objects.get( name=name )
    print( 'Network for Network "{0}"({1}) Address Block "{2}"({3}) Already Exists'.format( contractor_network[ 'name' ], args.network, contractor_addressblock[ 'name' ], args.address_block ) )
    sys.exit( 1 )

  except Network.DoesNotExist:
    pass

  network = Network()
  network.site = site
  network.name = name
  network.contractor_network_id = args.network
  network.contractor_addressblock_id = args.address_block
  network.monolithic = args.monolithic
  network.size = contractor_addressblock[ 'size' ]
  network.full_clean()
  network.save()

  print( 'Network for Network "{0}"({1}) Address Block "{2}"({3}) Created.'.format( contractor_network[ 'name' ], args.network, contractor_addressblock[ 'name' ], args.address_block ) )
  sys.exit( 0 )

if args.network_remove:
  try:
    network = Network.objects.get( name=args.network_remove )
  except Site.DoesNotExist:
    print( 'Network "{0}" not found in MCP'.format( args.network_remove ) )
    sys.exit( 1 )

  network.delete()
  print( 'Network "{0}" deleted.'.format( args.network_remove ) )
  sys.exit( 0 )

# dynamic resource options
if args.dynamic_resource_add:
  if not args.name or not args.description:
    print( 'Name and Description Required' )
    sys.exit( 1 )

  try:
    DynamicResource.objects.get( name=args.name )
    print( 'Dynamic Resource with Name "{0}" Already Exists'.format( args.name ) )
    sys.exit( 1 )

  except DynamicResource.DoesNotExist:
    pass

  dynamic_resource = DynamicResource()
  dynamic_resource.name = args.name
  dynamic_resource.description = args.description
  dynamic_resource.build_ahead_count = args.build_ahead_count
  dynamic_resource.full_clean()
  dynamic_resource.save()

  print( 'DynamicResource "{0}" Created.'.format( args.name ) )
  sys.exit( 0 )

if args.dynamic_resource_remove:
  try:
    dynamic_resource = DynamicResource.objects.get( name=args.dynamic_resource_remove )
  except DynamicResource.DoesNotExist:
    print( 'Dynamic Resource "{0}" not found in MCP'.format( args.dynamic_resource_remove ) )
    sys.exit( 1 )

  dynamic_resource.delete()
  print( 'Dynamic Resource "{0}" deleted.'.format( args.dynamic_resource_remove ) )
  sys.exit( 0 )

if args.dynamic_resource_attach:
  if not site or not args.name or not args.complex:
    print( 'Name, Site, and Complex Required' )
    sys.exit( 1 )

  try:
    dynamic_resource = DynamicResource.objects.get( name=args.name )
  except DynamicResource.DoesNotExist:
    print( 'Dynamic Resource "{0}" not found in MCP'.format( args.name ) )
    sys.exit( 1 )

  try:
    contractor_complex = contractor.getComplex( args.complex )
  except cinp.client.NotFound:
    print( 'Complex "{0}" not found on Contractor'.format( args.complex ) )
    sys.exit( 1 )

  drs = DynamicResourceSite()
  drs.dynamicresource = dynamic_resource
  drs.site = site
  drs.complex_id = args.complex
  drs.full_clean()
  drs.save()

  print( 'Site "{0}" attached to Dynamic Resource "{1}" with Complex "{2}"'.format( site.name, dynamic_resource.name, args.complex ) )
  sys.exit( 0 )

if args.dynamic_resource_detach:
  if not site or not args.name:
    print( 'Name and Site Required' )
    sys.exit( 1 )

  try:
    dynamic_resource = DynamicResource.objects.get( name=args.name )
  except DynamicResource.DoesNotExist:
    print( 'Dynamic Resource "{0}" not found in MCP'.format( args.name ) )
    sys.exit( 1 )

  try:
    dynamic_resource.dynamicresourcesite_set.get( site=site ).delete()
  except DynamicResourceSite.DoesNotExist:
    print( 'Site "{0}" for Dynamic Resource "{1}" does not exist'.format( site.name, args.name ) )
    sys.exit( 1 )

  print( 'Site "{0}" detached from Dynamic Resource "{1}" does not exist'.format( site.name, args.name ) )
  sys.exit( 0 )

if args.dynamic_resource_build_ahead:
  if not args.name or not args.blueprint:
    print( 'Name and BluePrint Required' )
    sys.exit( 1 )

  try:
    dynamic_resource = DynamicResource.objects.get( name=args.name )
  except DynamicResource.DoesNotExist:
    print( 'Dynamic Resource "{0}" not found in MCP'.format( args.name ) )
    sys.exit( 1 )

  if args.build_ahead_count:
    dynamic_resource.build_ahead_count_map[ args.blueprint ] = args.build_ahead_count
  else:
    try:
      del dynamic_resource.build_ahead_count_map[ args.blueprint ]
    except KeyError:
      pass

  dynamic_resource.full_clean()
  dynamic_resource.save()
  print( 'Set blueprint "{0}" to count "{1}" in Dynamic Resource "{2}"'.format( args.blueprint, args.build_ahead_count, args.name ) )
  sys.exit( 0 )

# the temporary hack
if args.update_builtin:
  try:
    resource = DynamicResource.objects.get()
  except DynamicResource.DoesNotExist:
    print( 'no dynamic resources found' )
    sys.exit( 1 )

  try:
    project = Project.objects.get( name='_builtin_' )
  except Project.DoesNotExist:
    project = Project( name='_builtin_' )
    project.local_path = ''
    project.last_checked = datetime.now( timezone.utc )
    project.full_clean()
    project.save()

  build = Build( name=args.update_builtin, project=project )
  build.manual = False
  build.full_clean()
  build.save()

  br = BuildResource( name=args.update_builtin, build=build, resource=resource )
  br.quantity = 1
  br.blueprint = args.update_builtin
  br.autorun = False
  br.full_clean()
  br.save()

  print( 'blueprint "{0}" added to builting project'.format( args.update_builtin ) )

  sys.exit( 0 )

print( 'No Action specified' )
sys.exit( 1 )
