#!/usr/bin/env python3
import os

os.environ.setdefault( 'DJANGO_SETTINGS_MODULE', 'mcp.settings' )

import django
django.setup()

import sys
import argparse
import getpass

from django.contrib.auth.models import User, Permission

parser = argparse.ArgumentParser( description='MCP SetupWizard, must be run as root' )
parser.add_argument( '--root-password', help='password to use for the root user, if not specified it will be prompted for' )

args = parser.parse_args()

if os.getuid() != 0:
  print( 'This must be run as root' )
  sys.exit( 1 )

if args.root_password:
  root_password = args.root_password
else:
  print( 'Please Specify the password to use for the root user' )
  root_password = getpass.getpass()

print( 'Creating users...' )
User.objects.create_superuser( username='root', password=root_password, email='root@localhost' )

u = User.objects.create_user( 'manager', password='manager' )
for name in ( 'can_build', 'can_ran', 'can_ack' ):
  u.user_permissions.add( Permission.objects.get( codename=name ) )

u = User.objects.create_user( 'dev', password='dev' )
for name in ( 'can_ack', ):
  u.user_permissions.add( Permission.objects.get( codename=name ) )

sys.exit( 0 )
